# --- Common specific parameters ------------------------------------------------------------------------------
inputDataFile        : "DATA/project.1.dat"        # Input DAT file
solutionFile         : "SOLUTIONS/project.1.sol"     # Output DAT file (solution)
solver               : "Greedy"                      # Supported solvers: Greedy / localSearch / GRASP
verbose              : True                         # Verbose mode?

# --- Greedy / Random specific parameters ---------------------------------------------------------------------
# No specific parameters
